### ISSUE TITLE
Introduction-Fun Fact About Me: best hiking location (Github Issues Exercise)

### ISSUE THREAD

**Issue by williamnorfolk** [epid8060fall2019/TrangQuach-introduction#1]
Hi Trang!

Great to meet you in your introduction!

In your introduction page under _Fun Fact About Me_ I see that you enjoy hiking. I also really enjoy hiking and I am always on the lookout for new places to go. What was your favorite hike that you have ever been on? Also do you have a favorite spot that is close to Athens?

Thanks!
William

**Comment by TrangQuach** [comment]
Hi William,

Thank you for your comment. I visited some places in GA such Raven Cliff Falls, Amicalola Falls State Park, Stone mountain, Helen city and Sandy Creek park. In Athens, Sandy Creek park is a good place and only 15 miles away from HSC campus.

**Comment by TrangQuach** [comment]
I updated information about some places to hike in Georgia on my introduction website.
